ALTER TABLE roles
    CHANGE COLUMN slug code VARCHAR(100) NOT NULL UNIQUE;

ALTER TABLE permissions
    ADD COLUMN name VARCHAR(150) NOT NULL AFTER action,
    ADD COLUMN is_active BOOLEAN NOT NULL DEFAULT TRUE AFTER description,
    CHANGE COLUMN slug code VARCHAR(150) NOT NULL UNIQUE;
